-- use this file to map the AP location ids to your locations
-- first value is the code of the target location/item and the second is the item type override (feel free to expand the table with any other values you might need (i.e. special initial values, increments, etc.)!)
-- to reference a location in Pop use @ in the beginning and then path to the section (more info: https://github.com/black-sliver/PopTracker/blob/master/doc/PACKS.md#locations)
-- to reference an item use it's code
-- here are the SM locations as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/location_mapping.lua
--BASE_LOCATION_ID = 0
--LOCATION_MAPPING = {
--	[BASE_LOCATION_ID + 00001] = { {"@Example Parent/Example Location 1/Example Section 1" } },
--	[BASE_LOCATION_ID + 00002] = { {"toggle" } },
	-- multiple locations on this id
--	[BASE_LOCATION_ID + 00003] = { {"@Example Parent/Example Location 1/Example Section 1"} }, {{"@Example Parent/Example Location 1/Example Section 2" } },
--}

BASE_POKEMON_LOCATION_ID = 0
-- Multiple Base IDs for different location types
MINIGAME_BASE_ID = 400000  -- BERRIES["100 Berries"]
QUEST_BASE_ID = 100000     -- BERRIES["10 Berries"] 
POWER_THUNDERBOLT_BASE_ID = 10000000  -- POWERS["Progressive Thunderbolt"]
POWER_DASH_BASE_ID = 20000000         -- POWERS["Progressive Dash"]
POWER_HEALTH_BASE_ID = 30000000       -- POWERS["Progressive Health"]
POWER_IRON_TAIL_BASE_ID = 40000000    -- POWERS["Progressive Iron Tail"]

LOCATION_MAPPING = {
	-- Treehouse
	[POWER_THUNDERBOLT_BASE_ID + 1] = {{"@Treehouse/Thunderbolt/Upgrade 1"}},
	[POWER_THUNDERBOLT_BASE_ID + 2] ={{"@Treehouse/Thunderbolt/Upgrade 2"}},
	[POWER_THUNDERBOLT_BASE_ID + 3] ={{"@Treehouse/Thunderbolt/Upgrade 3"}},
	[POWER_DASH_BASE_ID + 1] ={{"@Treehouse/Dash/Upgrade 1"}},
	[POWER_DASH_BASE_ID + 2] ={{"@Treehouse/Dash/Upgrade 2"}},
	[POWER_DASH_BASE_ID + 3] ={{"@Treehouse/Dash/Upgrade 3"}},
	[POWER_HEALTH_BASE_ID + 1] ={{"@Treehouse/Health/Upgrade 1"}},
	[POWER_HEALTH_BASE_ID + 2] ={{"@Treehouse/Health/Upgrade 2"}},
	[POWER_HEALTH_BASE_ID + 3] ={{"@Treehouse/Health/Upgrade 3"}},
	[POWER_IRON_TAIL_BASE_ID + 1] ={{"@Treehouse/Iron Tail/Upgrade 1"}},
	[POWER_IRON_TAIL_BASE_ID + 2] ={{"@Treehouse/Iron Tail/Upgrade 2"}},
	[POWER_IRON_TAIL_BASE_ID + 3] ={{"@Treehouse/Iron Tail/Upgrade 3"}},
	[BASE_POKEMON_LOCATION_ID + 00178] = { { "@Treehouse/Mime Jr./Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00177] = { { "@Treehouse/Burmy/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00179 + 01000] = { { "@Treehouse/Abra/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00176] = { { "@Treehouse/Drifblim/Friendship" } },

	-- Meadow Zone
	[BASE_POKEMON_LOCATION_ID + 00012] = { { "@Meadow Zone/Overworld Pokemon Treehouse Entrance/Aipom Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 11000] = { { "@Meadow Zone/Overworld Pokemon Treehouse Entrance/Aipom Friendship - Pokemon Unlock" } },
	[BASE_POKEMON_LOCATION_ID + 00013] = { { "@Meadow Zone/Overworld Pokemon Treehouse Entrance/Ambipom Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00008] = { { "@Meadow Zone/Overworld Pokemon Treehouse Entrance/Mankey Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00011] = { { "@Meadow Zone/Overworld Pokemon Treehouse Entrance/Oddish Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00004] = { { "@Meadow Zone/Overworld Pokemon Treehouse Entrance/Torterra Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00027] = { { "@Meadow Zone/Weedle/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 12000] = { { "@Meadow Zone/Weedle/Tree Dash" } },
	[BASE_POKEMON_LOCATION_ID + 00024] = { { "@Meadow Zone/Magikarp/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 14000] = { { "@Meadow Zone/Magikarp/electrocuted" } },
	[BASE_POKEMON_LOCATION_ID + 00028] = { { "@Meadow Zone/Shroomish/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 13000] = { { "@Meadow Zone/Shroomish/Crate Dash" } },
	[BASE_POKEMON_LOCATION_ID + 00016] = { { "@Meadow Zone/Croagunk/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 07000] = { { "@Meadow Zone/Croagunk/Friendship - Pokemon Unlock" } },
	[BASE_POKEMON_LOCATION_ID + 00025] = { { "@Meadow Zone/Caterpie/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 08000] = { { "@Meadow Zone/Caterpie/Tree Dash" } },
	[BASE_POKEMON_LOCATION_ID + 09000] = { { "@Meadow Zone/Caterpie/Friendship - Pokemon Unlock" } },
	[BASE_POKEMON_LOCATION_ID + 00017] = { { "@Meadow Zone/Overworld Pokemon Bridge Entrance/Starly Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00026] = { { "@Meadow Zone/Overworld Pokemon Bridge Entrance/Butterfree Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00007] = { { "@Meadow Zone/Overworld Pokemon Bridge Entrance/Treecko Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00021] = { { "@Meadow Zone/Overworld Pokemon Bridge Entrance/Lotad Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00014] = { { "@Meadow Zone/Overworld Pokemon Leafeon Place/Leafeon Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00023] = { { "@Meadow Zone/Overworld Pokemon Leafeon Place/Scyther Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00015] = { { "@Meadow Zone/Overworld Pokemon Spearow Attraction/Spearow Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00019] = { { "@Meadow Zone/Overworld Pokemon Spearow Attraction/Sudowoodo Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00018] = { { "@Meadow Zone/Overworld Pokemon Bulbasaur Area/Bonsly Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 04000] = { { "@Meadow Zone/Overworld Pokemon Bulbasaur Area/Bonsly Friendship - Pokemon Unlock" } },
	[BASE_POKEMON_LOCATION_ID + 00003] = { { "@Meadow Zone/Overworld Pokemon Bulbasaur Area/Turtwig Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 02000] = { { "@Meadow Zone/Overworld Pokemon Bulbasaur Area/Turtwig Friendship - Pokemon Unlock" } },
	[BASE_POKEMON_LOCATION_ID + 00020] = { { "@Meadow Zone/Overworld Pokemon Bulbasaur Area/Pachirisu Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00005] = { { "@Meadow Zone/Overworld Pokemon Bulbasaur Area/Buneary Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 05000] = { { "@Meadow Zone/Overworld Pokemon Bulbasaur Area/Buneary Friendship - Pokemon Unlock" } },
	[BASE_POKEMON_LOCATION_ID + 00006] = { { "@Meadow Zone/Overworld Pokemon Bulbasaur Area/Munchlax Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 01000] = { { "@Meadow Zone/Overworld Pokemon Bulbasaur Area/Munchlax Friendship - Pokemon Unlock" } },
	[BASE_POKEMON_LOCATION_ID + 00022] = { { "@Meadow Zone/Shinx/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00102] = { { "@Meadow Zone/Overworld Pokemon Bidoof Area/Chimchar Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00029] = { { "@Meadow Zone/Overworld Pokemon Bidoof Area/Tropius Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00010] = { { "@Meadow Zone/Overworld Pokemon Bidoof Area/Bibarel Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00009] = { { "@Meadow Zone/Bidoof/Friendship" } },
	[QUEST_BASE_ID + 1] = { { "@Meadow Zone/Bidoof/Housing 1" } },
	[BASE_POKEMON_LOCATION_ID + 15000] = { { "@Meadow Zone/Bidoof/Housing 1 - Pokemon Unlock" } },
	[QUEST_BASE_ID + 2] = { { "@Meadow Zone/Bidoof/Housing 2" } },
	[BASE_POKEMON_LOCATION_ID + 16000] = { { "@Meadow Zone/Bidoof/Housing 2 - Pokemon Unlock" } },
	[QUEST_BASE_ID + 3] = { { "@Meadow Zone/Bidoof/Housing 3" } },
	[BASE_POKEMON_LOCATION_ID + 17000] = { { "@Meadow Zone/Bidoof/Housing 3 - Pokemon Unlock" } },
	[QUEST_BASE_ID + 4] = { { "@Meadow Zone/Bidoof/Housing 4" } },
	[BASE_POKEMON_LOCATION_ID + 18000] = { { "@Meadow Zone/Bidoof/Housing 4 - Pokemon Unlock" } },

	-- Meadow Zone Bulbasaur's Daring Dash
	[BASE_POKEMON_LOCATION_ID + 00030] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Bulbasaur Friendship"}},
	[BASE_POKEMON_LOCATION_ID + 1000000] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Prisma"}},
	[MINIGAME_BASE_ID + 1] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Pikachu"}},
	[MINIGAME_BASE_ID + 2] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Turtwig"}},
	[MINIGAME_BASE_ID + 3] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Munchlax"}},
	[MINIGAME_BASE_ID + 4] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Chimchar"}},
	[MINIGAME_BASE_ID + 5] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Treecko"}},
	[MINIGAME_BASE_ID + 6] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Bibarel"}},
	[MINIGAME_BASE_ID + 7] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Bulbasaur"}},
	[MINIGAME_BASE_ID + 8] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Bidoof"}},
	[MINIGAME_BASE_ID + 9] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Oddish"}},
	[MINIGAME_BASE_ID + 10] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Shroomish"}},
	[MINIGAME_BASE_ID + 11] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Bonsly"}},
	[MINIGAME_BASE_ID + 12] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Lotad"}},
	[MINIGAME_BASE_ID + 13] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Weedle"}},
	[MINIGAME_BASE_ID + 14] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Caterpie"}},
	[MINIGAME_BASE_ID + 15] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Magikarp"}},
	[MINIGAME_BASE_ID + 16] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Jolteon"}},
	[MINIGAME_BASE_ID + 17] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Arcanine"}},
	[MINIGAME_BASE_ID + 18] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Leafeon"}},
	[MINIGAME_BASE_ID + 19] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Scyther"}},
	[MINIGAME_BASE_ID + 20] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Ponyta"}},
	[MINIGAME_BASE_ID + 21] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Shinx"}},
	[MINIGAME_BASE_ID + 22] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Eevee"}},
	[MINIGAME_BASE_ID + 23] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Pachirisu"}},
	[MINIGAME_BASE_ID + 24] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Buneary"}},
	[MINIGAME_BASE_ID + 25] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Croagunk"}},
	[MINIGAME_BASE_ID + 221] ={{"@Meadow Zone/Bulbasaur's Daring Dash Minigame/Mew"}},

	-- Meadow Zone Venusaur Minigame
	[BASE_POKEMON_LOCATION_ID + 2000000] ={{"@Meadow Zone/Venusaur's Vine Swing/Prisma"}},
	[MINIGAME_BASE_ID + 26] ={{"@Meadow Zone/Venusaur's Vine Swing/Pikachu"}},
	[MINIGAME_BASE_ID + 27] ={{"@Meadow Zone/Venusaur's Vine Swing/Munchlax"}},
	[MINIGAME_BASE_ID + 28] ={{"@Meadow Zone/Venusaur's Vine Swing/Magikarp"}},
	[MINIGAME_BASE_ID + 29] ={{"@Meadow Zone/Venusaur's Vine Swing/Blaziken"}},
	[MINIGAME_BASE_ID + 30] ={{"@Meadow Zone/Venusaur's Vine Swing/Infernape"}},
	[MINIGAME_BASE_ID + 31] ={{"@Meadow Zone/Venusaur's Vine Swing/Lucario"}},
	[MINIGAME_BASE_ID + 32] ={{"@Meadow Zone/Venusaur's Vine Swing/Primeape"}},
	[MINIGAME_BASE_ID + 33] ={{"@Meadow Zone/Venusaur's Vine Swing/Tangrowth"}},
	[MINIGAME_BASE_ID + 34] ={{"@Meadow Zone/Venusaur's Vine Swing/Ambipom"}},
	[MINIGAME_BASE_ID + 35] ={{"@Meadow Zone/Venusaur's Vine Swing/Croagunk"}},
	[MINIGAME_BASE_ID + 36] ={{"@Meadow Zone/Venusaur's Vine Swing/Mankey"}},
	[MINIGAME_BASE_ID + 37] ={{"@Meadow Zone/Venusaur's Vine Swing/Aipom"}},
	[MINIGAME_BASE_ID + 38] ={{"@Meadow Zone/Venusaur's Vine Swing/Chimchar"}},
	[MINIGAME_BASE_ID + 39] ={{"@Meadow Zone/Venusaur's Vine Swing/Treecko"}},
	[MINIGAME_BASE_ID + 40] ={{"@Meadow Zone/Venusaur's Vine Swing/Pachirisu"}},
	[MINIGAME_BASE_ID + 222] ={{"@Meadow Zone/Venusaur's Vine Swing/Jirachi"}},
	[BASE_POKEMON_LOCATION_ID + 00181] ={{"@Meadow Zone/Venusaur's Vine Swing/Jirachi Unlock"}},


	--Beach Zone
	[BASE_POKEMON_LOCATION_ID + 00033] = { { "@Beach Zone/Overworld Pokemon Treehouse Entrance/Slowpoke Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00043] = { { "@Beach Zone/Overworld Pokemon Treehouse Entrance/Psyduck Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 25000] = { { "@Beach Zone/Overworld Pokemon Treehouse Entrance/Psyduck Friendship - Pokemon Unlock" } },
	[BASE_POKEMON_LOCATION_ID + 00034] = { { "@Beach Zone/Overworld Pokemon Treehouse Entrance/Azurill Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 24000] = { { "@Beach Zone/Overworld Pokemon Treehouse Entrance/Azurill Friendship - Pokemon Unlock" } },
	[BASE_POKEMON_LOCATION_ID + 00045] = { { "@Beach Zone/Overworld Pokemon Treehouse Entrance/Buizel Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 22000] = { { "@Beach Zone/Overworld Pokemon Treehouse Entrance/Buizel Friendship - Pokemon Unlock" } },
	[BASE_POKEMON_LOCATION_ID + 00040] = { { "@Beach Zone/Overworld Pokemon Beach Area/Totodile Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00048] = { { "@Beach Zone/Overworld Pokemon Beach Area/Mudkip Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00054] = { { "@Beach Zone/Overworld Pokemon Beach Area/Blastoise Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00017 + 1000] = { { "@Beach Zone/Overworld Pokemon Beach Area/Starly Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00052] = { { "@Beach Zone/Overworld Pokemon Beach Area/Krabby Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00053] = { { "@Beach Zone/Overworld Pokemon Beach Area/Corphish Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00049] = { { "@Beach Zone/Overworld Pokemon Drifblim Area/Taillow Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00051] = { { "@Beach Zone/Overworld Pokemon Drifblim Area/Pidgeotto Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00055] = { { "@Beach Zone/Overworld Pokemon Drifblim Area/Wingull Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00050] = { { "@Beach Zone/Overworld Pokemon Drifblim Area/Staravia Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00035] = { { "@Beach Zone/Corsola/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00047] = { { "@Beach Zone/Overworld Pokemon West Area/Vaporeon Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00046] = { { "@Beach Zone/Overworld Pokemon West Area/Floatzel Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00044] = { { "@Beach Zone/Overworld Pokemon West Area/Golduck Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00041] = { { "@Beach Zone/Feraligatr/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00039] = { { "@Beach Zone/Wailord/Friendship" } },

	-- Beach Zone Recycling
	[QUEST_BASE_ID + 5] ={{"@Beach Zone/Recycle Box/Bottle 1"}},
	[QUEST_BASE_ID + 6] ={{"@Beach Zone/Recycle Box/Bottle 2"}},
	[BASE_POKEMON_LOCATION_ID + 26000] ={{"@Beach Zone/Recycle Box/Bottle 2 - Pokemon Unlock"}},
	[QUEST_BASE_ID + 7] ={{"@Beach Zone/Recycle Box/Bottle 3"}},
	[QUEST_BASE_ID + 8] ={{"@Beach Zone/Recycle Box/Bottle 4"}},
	[BASE_POKEMON_LOCATION_ID + 27000] ={{"@Beach Zone/Recycle Box/Bottle 4 - Pokemon Unlock"}},
	[QUEST_BASE_ID + 9] ={{"@Beach Zone/Recycle Box/Bottle 5"}},
	[QUEST_BASE_ID + 10] ={{"@Beach Zone/Recycle Box/Bottle 6"}},

	-- Beach Zone Pelipper's Circle Circuit
	[BASE_POKEMON_LOCATION_ID + 3000000] ={{"@Beach Zone/Pelipper's Circle Circuit/Prisma"}},
	[MINIGAME_BASE_ID + 41] ={{"@Beach Zone/Pelipper's Circle Circuit/Pikachu"}},
	[MINIGAME_BASE_ID + 42] ={{"@Beach Zone/Pelipper's Circle Circuit/Staraptor"}},
	[MINIGAME_BASE_ID + 43] ={{"@Beach Zone/Pelipper's Circle Circuit/Togekiss"}},
	[MINIGAME_BASE_ID + 44] ={{"@Beach Zone/Pelipper's Circle Circuit/Honchkrow"}},
	[MINIGAME_BASE_ID + 45] ={{"@Beach Zone/Pelipper's Circle Circuit/Gliscor"}},
	[MINIGAME_BASE_ID + 46] ={{"@Beach Zone/Pelipper's Circle Circuit/Pelipper"}},
	[MINIGAME_BASE_ID + 47] ={{"@Beach Zone/Pelipper's Circle Circuit/Staravia"}},
	[MINIGAME_BASE_ID + 48] ={{"@Beach Zone/Pelipper's Circle Circuit/Pidgeotto"}},
	[MINIGAME_BASE_ID + 49] ={{"@Beach Zone/Pelipper's Circle Circuit/Butterfree"}},
	[MINIGAME_BASE_ID + 50] ={{"@Beach Zone/Pelipper's Circle Circuit/Tropius"}},
	[MINIGAME_BASE_ID + 51] ={{"@Beach Zone/Pelipper's Circle Circuit/Murkrow"}},
	[MINIGAME_BASE_ID + 52] ={{"@Beach Zone/Pelipper's Circle Circuit/Taillow"}},
	[MINIGAME_BASE_ID + 53] ={{"@Beach Zone/Pelipper's Circle Circuit/Spearow"}},
	[MINIGAME_BASE_ID + 54] ={{"@Beach Zone/Pelipper's Circle Circuit/Starly"}},
	[MINIGAME_BASE_ID + 55] ={{"@Beach Zone/Pelipper's Circle Circuit/Wingull"}},
	[MINIGAME_BASE_ID + 223] ={{"@Beach Zone/Pelipper's Circle Circuit/Latias"}},
	[BASE_POKEMON_LOCATION_ID + 00183] ={{"@Beach Zone/Pelipper's Circle Circuit/Latias Unlock"}},

	-- Beach Zone Gyarados' Aqua Dash
		[BASE_POKEMON_LOCATION_ID + 4000000] ={{"@Beach Zone/Gyarados' Aqua Dash/Prisma"}},
	[MINIGAME_BASE_ID + 56] ={{"@Beach Zone/Gyarados' Aqua Dash/Pikachu"}},
	[MINIGAME_BASE_ID + 57] ={{"@Beach Zone/Gyarados' Aqua Dash/Psyduck"}},
	[MINIGAME_BASE_ID + 58] ={{"@Beach Zone/Gyarados' Aqua Dash/Azurill"}},
	[MINIGAME_BASE_ID + 59] ={{"@Beach Zone/Gyarados' Aqua Dash/Slowpoke"}},
	[MINIGAME_BASE_ID + 60] ={{"@Beach Zone/Gyarados' Aqua Dash/Empoleon"}},
	[MINIGAME_BASE_ID + 61] ={{"@Beach Zone/Gyarados' Aqua Dash/Floatzel"}},
	[MINIGAME_BASE_ID + 62] ={{"@Beach Zone/Gyarados' Aqua Dash/Feraligatr"}},
	[MINIGAME_BASE_ID + 63] ={{"@Beach Zone/Gyarados' Aqua Dash/Golduck"}},
	[MINIGAME_BASE_ID + 64] ={{"@Beach Zone/Gyarados' Aqua Dash/Vaporeon"}},
	[MINIGAME_BASE_ID + 65] ={{"@Beach Zone/Gyarados' Aqua Dash/Prinplup"}},
	[MINIGAME_BASE_ID + 66] ={{"@Beach Zone/Gyarados' Aqua Dash/Bibarel"}},
	[MINIGAME_BASE_ID + 67] ={{"@Beach Zone/Gyarados' Aqua Dash/Buizel"}},
	[MINIGAME_BASE_ID + 68] ={{"@Beach Zone/Gyarados' Aqua Dash/Corsola"}},
	[MINIGAME_BASE_ID + 69] ={{"@Beach Zone/Gyarados' Aqua Dash/Piplup"}},
	[MINIGAME_BASE_ID + 70] ={{"@Beach Zone/Gyarados' Aqua Dash/Lotad"}},
	[MINIGAME_BASE_ID + 224] ={{"@Beach Zone/Gyarados' Aqua Dash/Manaphy"}},
	[BASE_POKEMON_LOCATION_ID + 00182] ={{"@Beach Zone/Gyarados' Aqua Dash/Manaphy Unlock"}},

	-- Ice Zone
	[BASE_POKEMON_LOCATION_ID + 00042] = { { "@Ice Zone/Overworld Pokemon Lapras Area/Lapras Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00065] = { { "@Ice Zone/Overworld Pokemon Lapras Area/Spheal Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00052 + 1000] = { { "@Ice Zone/Overworld Pokemon Lapras Area/Krabby Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00048 + 1000] = { { "@Ice Zone/Overworld Pokemon Lapras Area/Mudkip Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00068] = { { "@Ice Zone/Overworld Pokemon Glalie Area/Octillery Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00062] = { { "@Ice Zone/Overworld Pokemon Glalie Area/Teddiursa Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00063] = { { "@Ice Zone/Overworld Pokemon Glalie Area/Ursaring Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00070] = { { "@Ice Zone/Overworld Pokemon Sneasel Area/Primeape Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00073] = { { "@Ice Zone/Overworld Pokemon Sneasel Area/Sneasel Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00058] = { { "@Ice Zone/Glalie/Friendship" } },
	[QUEST_BASE_ID + 11] = { { "@Ice Zone/Glalie/Igloo Quest 1" } },
	[BASE_POKEMON_LOCATION_ID + 38000] = { { "@Ice Zone/Glalie/Igloo Quest 1 - Pokemon Unlock" } },
	[QUEST_BASE_ID + 12] = { { "@Ice Zone/Glalie/Igloo Quest 2" } },
	[BASE_POKEMON_LOCATION_ID + 39000] = { { "@Ice Zone/Glalie/Igloo Quest 2 - Pokemon Unlock" } },
	[QUEST_BASE_ID + 13] = { { "@Ice Zone/Glalie/Igloo Quest 3" } },
	[BASE_POKEMON_LOCATION_ID + 00061] = { { "@Ice Zone/Mamoswine/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00049 + 1000] = { { "@Ice Zone/Overworld Pokemon Empoleon Entrance Area/Taillow Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00050 + 1000] = { { "@Ice Zone/Overworld Pokemon Empoleon Entrance Area/Staravia Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00060] = { { "@Ice Zone/Overworld Pokemon Empoleon Entrance Area/Piloswine Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00017 + 2000] = { { "@Ice Zone/Overworld Pokemon Christmas Tree/Starly Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00072] = { { "@Ice Zone/Overworld Pokemon Christmas Tree/Smoochum Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00071] = { { "@Ice Zone/Overworld Pokemon Christmas Tree/Squirtle Friendship" } },
	[QUEST_BASE_ID + 14] = { { "@Ice Zone/Christmas Tree/Present 1" } },
	[QUEST_BASE_ID + 15] = { { "@Ice Zone/Christmas Tree/Present 2" } },
	[QUEST_BASE_ID + 16] = { { "@Ice Zone/Christmas Tree/Present 3" } },
	[QUEST_BASE_ID + 17] = { { "@Ice Zone/Christmas Tree/Present 4" } },
	[BASE_POKEMON_LOCATION_ID + 00069] = { { "@Ice Zone/Christmas Tree/Delibird Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00064] = { { "@Ice Zone/Christmas Tree/Kirlia Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00074] = { { "@Ice Zone/Prinplup/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00067] = { { "@Ice Zone/Glaceon/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00053 + 1000] = { { "@Ice Zone/Overworld Pokemon Lower Lift Region/Corphish Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00055 + 1000] = { { "@Ice Zone/Overworld Pokemon Lower Lift Region/Wingull Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00066] = { { "@Ice Zone/Overworld Pokemon Lower Lift Region/Quagsire Friendship" } },

	-- Ice Zone Empoleon's Snow Slide
	[BASE_POKEMON_LOCATION_ID + 5000000] ={{"@Ice Zone/Empoleon's Snow Slide/Prisma"}},
	[MINIGAME_BASE_ID + 71] ={{"@Ice Zone/Empoleon's Snow Slide/Pikachu"}},
	[MINIGAME_BASE_ID + 72] ={{"@Ice Zone/Empoleon's Snow Slide/Teddiursa"}},
	[MINIGAME_BASE_ID + 73] ={{"@Ice Zone/Empoleon's Snow Slide/Magikarp"}},
	[MINIGAME_BASE_ID + 74] ={{"@Ice Zone/Empoleon's Snow Slide/Empoleon"}},
	[MINIGAME_BASE_ID + 75] ={{"@Ice Zone/Empoleon's Snow Slide/Glaceon"}},
	[MINIGAME_BASE_ID + 76] ={{"@Ice Zone/Empoleon's Snow Slide/Blastoise"}},
	[MINIGAME_BASE_ID + 77] ={{"@Ice Zone/Empoleon's Snow Slide/Glalie"}},
	[MINIGAME_BASE_ID + 78] ={{"@Ice Zone/Empoleon's Snow Slide/Lapras"}},
	[MINIGAME_BASE_ID + 79] ={{"@Ice Zone/Empoleon's Snow Slide/Delibird"}},
	[MINIGAME_BASE_ID + 80] ={{"@Ice Zone/Empoleon's Snow Slide/Piloswine"}},
	[MINIGAME_BASE_ID + 81] ={{"@Ice Zone/Empoleon's Snow Slide/Prinplup"}},
	[MINIGAME_BASE_ID + 82] ={{"@Ice Zone/Empoleon's Snow Slide/Squirtle"}},
	[MINIGAME_BASE_ID + 83] ={{"@Ice Zone/Empoleon's Snow Slide/Piplup"}},
	[MINIGAME_BASE_ID + 84] ={{"@Ice Zone/Empoleon's Snow Slide/Quagsire"}},
	[MINIGAME_BASE_ID + 85] ={{"@Ice Zone/Empoleon's Snow Slide/Spheal"}},
	[MINIGAME_BASE_ID + 225] ={{"@Ice Zone/Empoleon's Snow Slide/Suicune"}},
	[BASE_POKEMON_LOCATION_ID + 00184] ={{"@Ice Zone/Empoleon's Snow Slide/Suicune Unlock"}},

	-- Cavern Zone
	[BASE_POKEMON_LOCATION_ID + 00093] = { { "@Cavern Zone/Magnemite/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 40000] = { { "@Cavern Zone/Magnemite/Crate Dash" } },
	[BASE_POKEMON_LOCATION_ID + 00094] = { { "@Cavern Zone/Overworld Pokemon Magma Zone Entrance Area/Magnezone Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00018 + 1000] = { { "@Cavern Zone/Overworld Pokemon Magma Zone Entrance Area/Bonsly Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 04000 + 1] = { { "@Cavern Zone/Overworld Pokemon Magma Zone Entrance Area/Bonsly Friendship - Pokemon Unlock" } },
	[BASE_POKEMON_LOCATION_ID + 00084] = { { "@Cavern Zone/Overworld Pokemon Magma Zone Entrance Area/Dugtrio Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00078] = { { "@Cavern Zone/Overworld Pokemon Magma Zone Entrance Area/Aron Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00096] = { { "@Cavern Zone/Overworld Pokemon Magma Zone Entrance Area/Electivire Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00019 + 1000] = { { "@Cavern Zone/Overworld Pokemon Magma Zone Entrance Area/Sudowoodo Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00082] = { { "@Cavern Zone/Overworld Pokemon Middle Area/Golbat Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00081] = { { "@Cavern Zone/Overworld Pokemon Middle Area/Zubat Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00087 + 1000] = { { "@Cavern Zone/Overworld Pokemon Middle Area/Machamp - Battle Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 42000] = { { "@Cavern Zone/Magnemite 2/Crate Dash" } },
	[BASE_POKEMON_LOCATION_ID + 00093 + 1000] = { { "@Cavern Zone/Magnemite 2/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00086] = { { "@Cavern Zone/Overworld Pokemon Open Area/Geodude Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00087] = { { "@Cavern Zone/Overworld Pokemon Open Area/Machamp Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 41000] = { { "@Cavern Zone/Overworld Pokemon Open Area/Machamp Friendship - Pokemon Unlock" } },
	[BASE_POKEMON_LOCATION_ID + 00062 + 1000] = { { "@Cavern Zone/Overworld Pokemon Open Area/Teddiursa Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00088] = { { "@Cavern Zone/Overworld Pokemon Open Area/Meowth Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00092] = { { "@Cavern Zone/Overworld Pokemon Open Area/Raichu Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00095] = { { "@Cavern Zone/Overworld Pokemon Open Area/Hitmonlee Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00080] = { { "@Cavern Zone/Marowak/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00089] = { { "@Cavern Zone/Overworld Pokemon Deep Area/Scizor Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00091] = { { "@Cavern Zone/Overworld Pokemon Deep Area/Phanpy Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00090] = { { "@Cavern Zone/Overworld Pokemon Deep Area/Cranidos Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00119] = { { "@Cavern Zone/Overworld Pokemon Deep Area/Torchic Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00102 + 1000] = { { "@Cavern Zone/Overworld Pokemon Deep Area/Chimchar Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 44000] = { { "@Cavern Zone/Magnemite 3/Crate Dash" } },
	[BASE_POKEMON_LOCATION_ID + 00093 + 2000] = { { "@Cavern Zone/Magnemite 3/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 43000] = { { "@Cavern Zone/Diglett/Crate Dash" } },
	[BASE_POKEMON_LOCATION_ID + 00079] = { { "@Cavern Zone/Gible/Friendship" } },

	-- Cavern Zone Bastiodon's Panel Crush
	[BASE_POKEMON_LOCATION_ID + 6000000] ={{"@Cavern Zone/Bastiodon's Panel Crush/Prisma"}},
	[MINIGAME_BASE_ID + 86] ={{"@Cavern Zone/Bastiodon's Panel Crush/Pikachu"}},
	[MINIGAME_BASE_ID + 87] ={{"@Cavern Zone/Bastiodon's Panel Crush/Sableye"}},
	[MINIGAME_BASE_ID + 88] ={{"@Cavern Zone/Bastiodon's Panel Crush/Meowth"}},
	[MINIGAME_BASE_ID + 89] ={{"@Cavern Zone/Bastiodon's Panel Crush/Torchic"}},
	[MINIGAME_BASE_ID + 90] ={{"@Cavern Zone/Bastiodon's Panel Crush/Electivire"}},
	[MINIGAME_BASE_ID + 91] ={{"@Cavern Zone/Bastiodon's Panel Crush/Magmortar"}},
	[MINIGAME_BASE_ID + 92] ={{"@Cavern Zone/Bastiodon's Panel Crush/Hitmonlee"}},
	[MINIGAME_BASE_ID + 93] ={{"@Cavern Zone/Bastiodon's Panel Crush/Ursaring"}},
	[MINIGAME_BASE_ID + 94] ={{"@Cavern Zone/Bastiodon's Panel Crush/Mr. Mime"}},
	[MINIGAME_BASE_ID + 95] ={{"@Cavern Zone/Bastiodon's Panel Crush/Raichu"}},
	[MINIGAME_BASE_ID + 96] ={{"@Cavern Zone/Bastiodon's Panel Crush/Sudowoodo"}},
	[MINIGAME_BASE_ID + 97] ={{"@Cavern Zone/Bastiodon's Panel Crush/Charmander"}},
	[MINIGAME_BASE_ID + 98] ={{"@Cavern Zone/Bastiodon's Panel Crush/Gible"}},
	[MINIGAME_BASE_ID + 99] ={{"@Cavern Zone/Bastiodon's Panel Crush/Chimchar"}},
	[MINIGAME_BASE_ID + 100] ={{"@Cavern Zone/Bastiodon's Panel Crush/Magby"}},
	[MINIGAME_BASE_ID + 226] ={{"@Cavern Zone/Bastiodon's Panel Crush/Metagross"}},
	[BASE_POKEMON_LOCATION_ID + 00185] ={{"@Cavern Zone/Bastiodon's Panel Crush/Metagross Unlock"}},

	-- Magma Zone

	[BASE_POKEMON_LOCATION_ID + 00078 + 1000] = { { "@Magma Zone/Overworld Pokemon Entrance Area/Aron Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00119 + 1000] = { { "@Magma Zone/Overworld Pokemon Entrance Area/Torchic Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00102 + 2000] = { { "@Magma Zone/Overworld Pokemon Entrance Area/Chimchar Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 48000] = { { "@Magma Zone/Overworld Pokemon Entrance Area/Chimchar Friendship - Pokemon Unlock" } },
	[BASE_POKEMON_LOCATION_ID + 00086 + 1000] = { { "@Magma Zone/Overworld Pokemon Entrance Area/Geodude Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00018 + 2000] = { { "@Magma Zone/Overworld Pokemon Entrance Area/Bonsly Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00108] = { { "@Magma Zone/Overworld Pokemon Entrance Area/Magby Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00108 + 1000] = { { "@Magma Zone/Overworld Pokemon Entrance Area/Magby - Battle Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00104] = { { "@Magma Zone/Overworld Pokemon Entrance Area/Vulpix Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 49000] = { { "@Magma Zone/Overworld Pokemon Entrance Area/Vulpix Friendship - Pokemon Unlock" } },
	[BASE_POKEMON_LOCATION_ID + 00115] = { { "@Magma Zone/Overworld Pokemon Entrance Area/Baltoy Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 54000] = { { "@Magma Zone/Overworld Pokemon Entrance Area/Baltoy Friendship - Pokemon Unlock" } },
	[BASE_POKEMON_LOCATION_ID + 00099] = { { "@Magma Zone/Hitmontop/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00112] = { { "@Magma Zone/Torkoal/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00113] = { { "@Magma Zone/Golem/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00101] = { { "@Magma Zone/Camerupt/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 53000] = { { "@Magma Zone/Baltoy/Crate Dash" } },
	[BASE_POKEMON_LOCATION_ID + 00116] = { { "@Magma Zone/Claydol/Friendship" } },
	[QUEST_BASE_ID + 19] = { { "@Magma Zone/Rhyperior Quest/Iron Disc" } },
	[QUEST_BASE_ID + 18] = { { "@Magma Zone/Meditite/Quiz" } },
	[BASE_POKEMON_LOCATION_ID + 00105] = { { "@Magma Zone/Overworld Pokemon Circle Area/Ninetales Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00114] = { { "@Magma Zone/Overworld Pokemon Circle Area/Quilava Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00103] = { { "@Magma Zone/Overworld Pokemon Circle Area/Infernape Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00117] = { { "@Magma Zone/Overworld Pokemon Circle Area/Ponyta Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00100] = { { "@Magma Zone/Overworld Pokemon Circle Area/Hitmonchan Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00109] = { { "@Magma Zone/Overworld Pokemon Circle Area/Magmortar Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00106] = { { "@Magma Zone/Farfetch'd/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00120] = { { "@Magma Zone/Blaziken/Friendship" } },

	-- Magma Zone Rhyperior's Bumper Burn
	[BASE_POKEMON_LOCATION_ID + 7000000] = { { "@Magma Zone/Rhyperior's Bumper Burn/Prisma" } },
	[MINIGAME_BASE_ID + 101] ={{"@Magma Zone/Rhyperior's Bumper Burn/Pikachu"}},
	[MINIGAME_BASE_ID + 102] ={{"@Magma Zone/Rhyperior's Bumper Burn/Magnemite"}},
	[MINIGAME_BASE_ID + 103] ={{"@Magma Zone/Rhyperior's Bumper Burn/Rhyperior"}},
	[MINIGAME_BASE_ID + 104] ={{"@Magma Zone/Rhyperior's Bumper Burn/Tyranitar"}},
	[MINIGAME_BASE_ID + 105] ={{"@Magma Zone/Rhyperior's Bumper Burn/Hitmontop"}},
	[MINIGAME_BASE_ID + 106] ={{"@Magma Zone/Rhyperior's Bumper Burn/Flareon"}},
	[MINIGAME_BASE_ID + 107] ={{"@Magma Zone/Rhyperior's Bumper Burn/Venusaur"}},
	[MINIGAME_BASE_ID + 108] ={{"@Magma Zone/Rhyperior's Bumper Burn/Snorlax"}},
	[MINIGAME_BASE_ID + 109] ={{"@Magma Zone/Rhyperior's Bumper Burn/Torterra"}},
	[MINIGAME_BASE_ID + 110] ={{"@Magma Zone/Rhyperior's Bumper Burn/Magnezone"}},
	[MINIGAME_BASE_ID + 111] ={{"@Magma Zone/Rhyperior's Bumper Burn/Claydol"}},
	[MINIGAME_BASE_ID + 112] ={{"@Magma Zone/Rhyperior's Bumper Burn/Quilava"}},
	[MINIGAME_BASE_ID + 113] ={{"@Magma Zone/Rhyperior's Bumper Burn/Torkoal"}},
	[MINIGAME_BASE_ID + 114] ={{"@Magma Zone/Rhyperior's Bumper Burn/Baltoy"}},
	[MINIGAME_BASE_ID + 115] ={{"@Magma Zone/Rhyperior's Bumper Burn/Bonsly"}},
	[MINIGAME_BASE_ID + 227] ={{"@Magma Zone/Rhyperior's Bumper Burn/Heatran"}},
	[BASE_POKEMON_LOCATION_ID + 00186] ={{"@Magma Zone/Rhyperior's Bumper Burn/Heatran Unlock"}},

	-- Magma Zone Blaziken's Boulder Bash
	[BASE_POKEMON_LOCATION_ID + 8000000] = { { "@Magma Zone/Blaziken's Boulder Bash/Prisma" } },
	[MINIGAME_BASE_ID + 116] ={{"@Magma Zone/Blaziken's Boulder Bash/Pikachu"}},
	[MINIGAME_BASE_ID + 117] ={{"@Magma Zone/Blaziken's Boulder Bash/Geodude"}},
	[MINIGAME_BASE_ID + 118] ={{"@Magma Zone/Blaziken's Boulder Bash/Phanpy"}},
	[MINIGAME_BASE_ID + 119] ={{"@Magma Zone/Blaziken's Boulder Bash/Blaziken"}},
	[MINIGAME_BASE_ID + 120] ={{"@Magma Zone/Blaziken's Boulder Bash/Garchomp"}},
	[MINIGAME_BASE_ID + 121] ={{"@Magma Zone/Blaziken's Boulder Bash/Scizor"}},
	[MINIGAME_BASE_ID + 122] ={{"@Magma Zone/Blaziken's Boulder Bash/Magmortar"}},
	[MINIGAME_BASE_ID + 123] ={{"@Magma Zone/Blaziken's Boulder Bash/Hitmonchan"}},
	[MINIGAME_BASE_ID + 124] ={{"@Magma Zone/Blaziken's Boulder Bash/Machamp"}},
	[MINIGAME_BASE_ID + 125] ={{"@Magma Zone/Blaziken's Boulder Bash/Marowak"}},
	[MINIGAME_BASE_ID + 126] ={{"@Magma Zone/Blaziken's Boulder Bash/Farfetch'd"}},
	[MINIGAME_BASE_ID + 127] ={{"@Magma Zone/Blaziken's Boulder Bash/Cranidos"}},
	[MINIGAME_BASE_ID + 128] ={{"@Magma Zone/Blaziken's Boulder Bash/Camerupt"}},
	[MINIGAME_BASE_ID + 129] ={{"@Magma Zone/Blaziken's Boulder Bash/Bastiodon"}},
	[MINIGAME_BASE_ID + 130] ={{"@Magma Zone/Blaziken's Boulder Bash/Mawile"}},
	[MINIGAME_BASE_ID + 228] ={{"@Magma Zone/Blaziken's Boulder Bash/Groudon"}},
	[BASE_POKEMON_LOCATION_ID + 00187] ={{"@Magma Zone/Blaziken's Boulder Bash/Groudon Unlock"}},

	-- Haunted Zone
	[BASE_POKEMON_LOCATION_ID + 00124] = { { "@Haunted Zone/Drifloon/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00092 + 1000] = { { "@Haunted Zone/Raichu/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00088 + 1000] = { { "@Haunted Zone/Meowth/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00012 + 1000] = { { "@Haunted Zone/Overworld Pokemon Entrance Area/Aipom Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00013 + 1000] = { { "@Haunted Zone/Overworld Pokemon Entrance Area/Ambipom Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00123] = { { "@Haunted Zone/Overworld Pokemon Entrance Area/Gliscor Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00121] = { { "@Haunted Zone/Overworld Pokemon Left Area/Murkrow Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 57000] = { { "@Haunted Zone/Overworld Pokemon Left Area/Murkrow Friendship - Pokemon Unlock" } },
	[BASE_POKEMON_LOCATION_ID + 00122] = { { "@Haunted Zone/Overworld Pokemon Left Area/Honchkrow Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 58000] = { { "@Haunted Zone/Metapod/Tree Dash" } },
	[BASE_POKEMON_LOCATION_ID + 00126] = { { "@Haunted Zone/Metapod/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00125] = { { "@Haunted Zone/Kakuna/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 59000] = { { "@Haunted Zone/Kakuna/Tree Dash" } },

	-- Haunted Zone Tangrowth's Swing-Along

	[BASE_POKEMON_LOCATION_ID + 9000000] ={{"@Haunted Zone/Tangrowth's Swing-Along/Prisma"}},
	[MINIGAME_BASE_ID + 131] ={{"@Haunted Zone/Tangrowth's Swing-Along/Pikachu"}},
	[MINIGAME_BASE_ID + 132] ={{"@Haunted Zone/Tangrowth's Swing-Along/Meowth"}},
	[MINIGAME_BASE_ID + 133] ={{"@Haunted Zone/Tangrowth's Swing-Along/Pichu"}},
	[MINIGAME_BASE_ID + 134] ={{"@Haunted Zone/Tangrowth's Swing-Along/Lucario"}},
	[MINIGAME_BASE_ID + 135] ={{"@Haunted Zone/Tangrowth's Swing-Along/Infernape"}},
	[MINIGAME_BASE_ID + 136] ={{"@Haunted Zone/Tangrowth's Swing-Along/Blaziken"}},
	[MINIGAME_BASE_ID + 137] ={{"@Haunted Zone/Tangrowth's Swing-Along/Riolu"}},
	[MINIGAME_BASE_ID + 138] ={{"@Haunted Zone/Tangrowth's Swing-Along/Sneasel"}},
	[MINIGAME_BASE_ID + 139] ={{"@Haunted Zone/Tangrowth's Swing-Along/Raichu"}},
	[MINIGAME_BASE_ID + 140] ={{"@Haunted Zone/Tangrowth's Swing-Along/Ambipom"}},
	[MINIGAME_BASE_ID + 141] ={{"@Haunted Zone/Tangrowth's Swing-Along/Primeape"}},
	[MINIGAME_BASE_ID + 142] ={{"@Haunted Zone/Tangrowth's Swing-Along/Aipom"}},
	[MINIGAME_BASE_ID + 143] ={{"@Haunted Zone/Tangrowth's Swing-Along/Electabuzz"}},
	[MINIGAME_BASE_ID + 144] ={{"@Haunted Zone/Tangrowth's Swing-Along/Chimchar"}},
	[MINIGAME_BASE_ID + 145] ={{"@Haunted Zone/Tangrowth's Swing-Along/Croagunk"}},
	[MINIGAME_BASE_ID + 229] ={{"@Haunted Zone/Tangrowth's Swing-Along/Celebi"}},
	[BASE_POKEMON_LOCATION_ID + 00188] ={{"@Haunted Zone/Tangrowth's Swing-Along/Celebi Unlock"}},

	-- Haunted Zone Mansion

	[BASE_POKEMON_LOCATION_ID + 00147] = { { "@Haunted Zone/Duskull/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00135] = { { "@Haunted Zone/Overworld Pokemon Entrance/Elekid Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 62000] = { { "@Haunted Zone/Overworld Pokemon Entrance/Elekid Friendship - Pokemon Unlock" } },
	[BASE_POKEMON_LOCATION_ID + 00138] = { { "@Haunted Zone/Overworld Pokemon Entrance/Stunky Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 65000] = { { "@Haunted Zone/Overworld Pokemon Entrance/Stunky Friendship - Pokemon Unlock" } },
	[BASE_POKEMON_LOCATION_ID + 00136] = { { "@Haunted Zone/Overworld Pokemon Floor Area/Electabuzz Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00139] = { { "@Haunted Zone/Overworld Pokemon Floor Area/Skuntank Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00143] = { { "@Haunted Zone/Overworld Pokemon Floor Area/Espeon Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00142] = { { "@Haunted Zone/Overworld Pokemon Floor Area/Umbreon Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 73000] = { { "@Haunted Zone/Overworld Pokemon Floor Area/Umbreon Friendship - Pokemon Unlock" } },
	[BASE_POKEMON_LOCATION_ID + 00145] = { { "@Haunted Zone/Overworld Pokemon Floor Area/Haunter Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00144] = { { "@Haunted Zone/Overworld Pokemon Floor Area/Gastly Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00133] = { { "@Haunted Zone/Misdreavus/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00141] = { { "@Haunted Zone/Overworld Pokemon Dance Hall/Electrode Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00134] = { { "@Haunted Zone/Overworld Pokemon Dance Hall/Mismagius Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00137] = { { "@Haunted Zone/Overworld Pokemon Dance Hall/Luxray Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00132] = { { "@Haunted Zone/Pichu/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00140] = { { "@Haunted Zone/Voltorb/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 60000] = { { "@Haunted Zone/Voltorb/Vase Dash" } },
	[BASE_POKEMON_LOCATION_ID + 00146] = { { "@Haunted Zone/Gengar/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 74000] = { { "@Haunted Zone/Gengar/Painting" } },
	[BASE_POKEMON_LOCATION_ID + 00130] = { { "@Haunted Zone/Spinarak/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00131] = { { "@Haunted Zone/Breloom/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00179] = { { "@Haunted Zone/Abra/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00128] = { { "@Haunted Zone/Riolu/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00128] = { { "@Haunted Zone/Riolu/Friendship" } },

	-- Haunted Zone Mansion Dusknoir's Speed Slam
	[BASE_POKEMON_LOCATION_ID + 9000001] ={{"@Haunted Zone/Dusknoir's Speed Slam/Prisma"}},
	[MINIGAME_BASE_ID + 146] ={{"@Haunted Zone/Dusknoir's Speed Slam/Pikachu"}},
	[MINIGAME_BASE_ID + 147] ={{"@Haunted Zone/Dusknoir's Speed Slam/Stunky"}},
	[MINIGAME_BASE_ID + 148] ={{"@Haunted Zone/Dusknoir's Speed Slam/Gengar"}},
	[MINIGAME_BASE_ID + 149] ={{"@Haunted Zone/Dusknoir's Speed Slam/Mismagius"}},
	[MINIGAME_BASE_ID + 150] ={{"@Haunted Zone/Dusknoir's Speed Slam/Scizor"}},
	[MINIGAME_BASE_ID + 151] ={{"@Haunted Zone/Dusknoir's Speed Slam/Espeon"}},
	[MINIGAME_BASE_ID + 152] ={{"@Haunted Zone/Dusknoir's Speed Slam/Dusknoir"}},
	[MINIGAME_BASE_ID + 153] ={{"@Haunted Zone/Dusknoir's Speed Slam/Umbreon"}},
	[MINIGAME_BASE_ID + 154] ={{"@Haunted Zone/Dusknoir's Speed Slam/Cranidos"}},
	[MINIGAME_BASE_ID + 155] ={{"@Haunted Zone/Dusknoir's Speed Slam/Skuntank"}},
	[MINIGAME_BASE_ID + 156] ={{"@Haunted Zone/Dusknoir's Speed Slam/Electrode"}},
	[MINIGAME_BASE_ID + 157] ={{"@Haunted Zone/Dusknoir's Speed Slam/Gastly"}},
	[MINIGAME_BASE_ID + 158] ={{"@Haunted Zone/Dusknoir's Speed Slam/Duskull"}},
	[MINIGAME_BASE_ID + 159] ={{"@Haunted Zone/Dusknoir's Speed Slam/Misdreavus"}},
	[MINIGAME_BASE_ID + 160] ={{"@Haunted Zone/Dusknoir's Speed Slam/Krabby"}},
	[MINIGAME_BASE_ID + 230] ={{"@Haunted Zone/Dusknoir's Speed Slam/Darkrai"}},
	[BASE_POKEMON_LOCATION_ID + 00189] ={{"@Haunted Zone/Dusknoir's Speed Slam/Darkrai Unlock"}},

	-- Haunted Zone Mansion Rotom's Spooky Shoot-'em-Up
	[BASE_POKEMON_LOCATION_ID + 9000002] ={{"@Haunted Zone/Rotom's Spooky Shoot-'em-Up/Prisma"}},
	[MINIGAME_BASE_ID + 161] ={{"@Haunted Zone/Rotom's Spooky Shoot-'em-Up/Pikachu"}},
	[MINIGAME_BASE_ID + 162] ={{"@Haunted Zone/Rotom's Spooky Shoot-'em-Up/Magnemite"}},
	[MINIGAME_BASE_ID + 163] ={{"@Haunted Zone/Rotom's Spooky Shoot-'em-Up/Porygon-Z"}},
	[MINIGAME_BASE_ID + 164] ={{"@Haunted Zone/Rotom's Spooky Shoot-'em-Up/Magnezone"}},
	[MINIGAME_BASE_ID + 165] ={{"@Haunted Zone/Rotom's Spooky Shoot-'em-Up/Gengar"}},
	[MINIGAME_BASE_ID + 166] ={{"@Haunted Zone/Rotom's Spooky Shoot-'em-Up/Magmortar"}},
	[MINIGAME_BASE_ID + 167] ={{"@Haunted Zone/Rotom's Spooky Shoot-'em-Up/Electivire"}},
	[MINIGAME_BASE_ID + 168] ={{"@Haunted Zone/Rotom's Spooky Shoot-'em-Up/Mismagius"}},
	[MINIGAME_BASE_ID + 169] ={{"@Haunted Zone/Rotom's Spooky Shoot-'em-Up/Claydol"}},
	[MINIGAME_BASE_ID + 170] ={{"@Haunted Zone/Rotom's Spooky Shoot-'em-Up/Electabuzz"}},
	[MINIGAME_BASE_ID + 171] ={{"@Haunted Zone/Rotom's Spooky Shoot-'em-Up/Haunter"}},
	[MINIGAME_BASE_ID + 172] ={{"@Haunted Zone/Rotom's Spooky Shoot-'em-Up/Abra"}},
	[MINIGAME_BASE_ID + 173] ={{"@Haunted Zone/Rotom's Spooky Shoot-'em-Up/Elekid"}},
	[MINIGAME_BASE_ID + 174] ={{"@Haunted Zone/Rotom's Spooky Shoot-'em-Up/Mr. Mime"}},
	[MINIGAME_BASE_ID + 175] ={{"@Haunted Zone/Rotom's Spooky Shoot-'em-Up/Baltoy"}},
	[MINIGAME_BASE_ID + 231] ={{"@Haunted Zone/Rotom's Spooky Shoot-'em-Up/Rotom"}},
	[BASE_POKEMON_LOCATION_ID + 00190] ={{"@Haunted Zone/Rotom's Spooky Shoot-'em-Up/Rotom Unlock"}},


	-- Granite Zone
	[BASE_POKEMON_LOCATION_ID + 00155] = { { "@Granite Zone/Overworld Pokemon Entrance Area/Lopunny Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00159] = { { "@Granite Zone/Overworld Pokemon Entrance Area/Eevee Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 78000] = { { "@Granite Zone/Overworld Pokemon Entrance Area/Eevee Friendship - Pokemon Unlock" } },
	[BASE_POKEMON_LOCATION_ID + 00156] = { { "@Granite Zone/Overworld Pokemon Entrance Area/Furret Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00164] = { { "@Granite Zone/Overworld Pokemon Entrance Area/Tyranitar Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00149] = { { "@Granite Zone/Overworld Pokemon Absol Area/Charizard Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00124 + 1000] = { { "@Granite Zone/Overworld Pokemon Absol Area/Drifloon Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00115 + 1000] = { { "@Granite Zone/Overworld Pokemon Absol Area/Baltoy Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 54000 + 1] = { { "@Granite Zone/Overworld Pokemon Absol Area/Baltoy Friendship - Pokemon Unlock" } },
	[BASE_POKEMON_LOCATION_ID + 00150] = { { "@Granite Zone/Flygon/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00158] = { { "@Granite Zone/Skorupi/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00151] = { { "@Granite Zone/Porygon-Z/Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00080 + 1000] = { { "@Granite Zone/Overworld Pokemon Pyramid Area/Marowak Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00116 + 1000] = { { "@Granite Zone/Overworld Pokemon Pyramid Area/Claydol Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00157] = { { "@Granite Zone/Overworld Pokemon Salamence Area/Staraptor Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 79000] = { { "@Granite Zone/Overworld Pokemon Salamence Area/Staraptor Friendship - Pokemon Unlock" } },
	[BASE_POKEMON_LOCATION_ID + 00162] = { { "@Granite Zone/Overworld Pokemon Salamence Area/Aerodactyl Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00154] = { { "@Granite Zone/Overworld Pokemon Salamence Area/Arcanine Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00049 + 2000] = { { "@Granite Zone/Overworld Pokemon Salamence Area/Taillow Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00163] = { { "@Granite Zone/Overworld Pokemon Salamence Area/Jolteon Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00165] = { { "@Granite Zone/Overworld Pokemon Salamence Area/Garchomp Friendship" } },

	-- Granite Zone Absol's Hurdle Bounce

	[BASE_POKEMON_LOCATION_ID + 9000003] ={{"@Granite Zone/Absol's Hurdle Bounce/Prisma"}},
	[MINIGAME_BASE_ID + 176] ={{"@Granite Zone/Absol's Hurdle Bounce/Pikachu"}},
	[MINIGAME_BASE_ID + 177] ={{"@Granite Zone/Absol's Hurdle Bounce/Chikorita"}},
	[MINIGAME_BASE_ID + 178] ={{"@Granite Zone/Absol's Hurdle Bounce/Absol"}},
	[MINIGAME_BASE_ID + 179] ={{"@Granite Zone/Absol's Hurdle Bounce/Lucario"}},
	[MINIGAME_BASE_ID + 180] ={{"@Granite Zone/Absol's Hurdle Bounce/Ponyta"}},
	[MINIGAME_BASE_ID + 181] ={{"@Granite Zone/Absol's Hurdle Bounce/Ninetales"}},
	[MINIGAME_BASE_ID + 182] ={{"@Granite Zone/Absol's Hurdle Bounce/Lopunny"}},
	[MINIGAME_BASE_ID + 183] ={{"@Granite Zone/Absol's Hurdle Bounce/Espeon"}},
	[MINIGAME_BASE_ID + 184] ={{"@Granite Zone/Absol's Hurdle Bounce/Infernape"}},
	[MINIGAME_BASE_ID + 185] ={{"@Granite Zone/Absol's Hurdle Bounce/Breloom"}},
	[MINIGAME_BASE_ID + 186] ={{"@Granite Zone/Absol's Hurdle Bounce/Riolu"}},
	[MINIGAME_BASE_ID + 187] ={{"@Granite Zone/Absol's Hurdle Bounce/Furret"}},
	[MINIGAME_BASE_ID + 188] ={{"@Granite Zone/Absol's Hurdle Bounce/Mareep"}},
	[MINIGAME_BASE_ID + 189] ={{"@Granite Zone/Absol's Hurdle Bounce/Eevee"}},
	[MINIGAME_BASE_ID + 190] ={{"@Granite Zone/Absol's Hurdle Bounce/Vulpix"}},
	[MINIGAME_BASE_ID + 232] ={{"@Granite Zone/Absol's Hurdle Bounce/Shaymin"}},
	[BASE_POKEMON_LOCATION_ID + 00191] ={{"@Granite Zone/Absol's Hurdle Bounce/Shaymin Unlock"}},

	-- Granite Zone Salamence's Sky Race

	[BASE_POKEMON_LOCATION_ID + 9000004] ={{"@Granite Zone/Salamence's Sky Race/Prisma"}},
	[MINIGAME_BASE_ID + 191] ={{"@Granite Zone/Salamence's Sky Race/Pikachu"}},
	[MINIGAME_BASE_ID + 192] ={{"@Granite Zone/Salamence's Sky Race/Salamence"}},
	[MINIGAME_BASE_ID + 193] ={{"@Granite Zone/Salamence's Sky Race/Charizard"}},
	[MINIGAME_BASE_ID + 194] ={{"@Granite Zone/Salamence's Sky Race/Dragonite"}},
	[MINIGAME_BASE_ID + 195] ={{"@Granite Zone/Salamence's Sky Race/Flygon"}},
	[MINIGAME_BASE_ID + 196] ={{"@Granite Zone/Salamence's Sky Race/Aerodactyl"}},
	[MINIGAME_BASE_ID + 197] ={{"@Granite Zone/Salamence's Sky Race/Staraptor"}},
	[MINIGAME_BASE_ID + 198] ={{"@Granite Zone/Salamence's Sky Race/Honchkrow"}},
	[MINIGAME_BASE_ID + 199] ={{"@Granite Zone/Salamence's Sky Race/Gliscor"}},
	[MINIGAME_BASE_ID + 200] ={{"@Granite Zone/Salamence's Sky Race/Pidgeotto"}},
	[MINIGAME_BASE_ID + 201] ={{"@Granite Zone/Salamence's Sky Race/Togekiss"}},
	[MINIGAME_BASE_ID + 202] ={{"@Granite Zone/Salamence's Sky Race/Golbat"}},
	[MINIGAME_BASE_ID + 203] ={{"@Granite Zone/Salamence's Sky Race/Taillow"}},
	[MINIGAME_BASE_ID + 204] ={{"@Granite Zone/Salamence's Sky Race/Murkrow"}},
	[MINIGAME_BASE_ID + 205] ={{"@Granite Zone/Salamence's Sky Race/Zubat"}},
	[MINIGAME_BASE_ID + 233] ={{"@Granite Zone/Salamence's Sky Race/Latios"}},
	[BASE_POKEMON_LOCATION_ID + 00192] ={{"@Granite Zone/Salamence's Sky Race/Latios Unlock"}},


	-- Flower Zone
	[BASE_POKEMON_LOCATION_ID + 00170] = { { "@Flower Zone/Overworld Pokemon Rayquaza Area/Skiploom Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00169] = { { "@Flower Zone/Overworld Pokemon Rayquaza Area/Budew Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00173] = { { "@Flower Zone/Overworld Pokemon Rayquaza Area/Dragonite Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00172] = { { "@Flower Zone/Overworld Pokemon Rayquaza Area/Mareep Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00171] = { { "@Flower Zone/Overworld Pokemon Shaymin Area/Cyndaquil Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00174] = { { "@Flower Zone/Overworld Pokemon Shaymin Area/Lucario Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00156 + 1000] = { { "@Flower Zone/Overworld Pokemon Shaymin Area/Furret Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00062 + 2000] = { { "@Flower Zone/Overworld Pokemon Shaymin Area/Teddiursa Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00107 + 1000] = { { "@Flower Zone/Overworld Pokemon Shaymin Area/Meditite Friendship" } },
	[BASE_POKEMON_LOCATION_ID + 00168] = { { "@Flower Zone/Overworld Pokemon Shaymin Area/Bellossom Friendship" } },


	-- Flower Zone Rayquaza's Balloon Panic
	[BASE_POKEMON_LOCATION_ID + 9000005] ={{"@Flower Zone/Rayquaza's Balloon Panic/Prisma"}},
	[MINIGAME_BASE_ID + 206] ={{"@Flower Zone/Rayquaza's Balloon Panic/Pikachu"}},
	[MINIGAME_BASE_ID + 207] ={{"@Flower Zone/Rayquaza's Balloon Panic/Lucario"}},
	[MINIGAME_BASE_ID + 208] ={{"@Flower Zone/Rayquaza's Balloon Panic/Glaceon"}},
	[MINIGAME_BASE_ID + 209] ={{"@Flower Zone/Rayquaza's Balloon Panic/Luxray"}},
	[MINIGAME_BASE_ID + 210] ={{"@Flower Zone/Rayquaza's Balloon Panic/Mamoswine"}},
	[MINIGAME_BASE_ID + 211] ={{"@Flower Zone/Rayquaza's Balloon Panic/Infernape"}},
	[MINIGAME_BASE_ID + 212] ={{"@Flower Zone/Rayquaza's Balloon Panic/Floatzel"}},
	[MINIGAME_BASE_ID + 213] ={{"@Flower Zone/Rayquaza's Balloon Panic/Rhyperior"}},
	[MINIGAME_BASE_ID + 214] ={{"@Flower Zone/Rayquaza's Balloon Panic/Absol"}},
	[MINIGAME_BASE_ID + 215] ={{"@Flower Zone/Rayquaza's Balloon Panic/Breloom"}},
	[MINIGAME_BASE_ID + 216] ={{"@Flower Zone/Rayquaza's Balloon Panic/Mareep"}},
	[MINIGAME_BASE_ID + 217] ={{"@Flower Zone/Rayquaza's Balloon Panic/Cyndaquil"}},
	[MINIGAME_BASE_ID + 218] ={{"@Flower Zone/Rayquaza's Balloon Panic/Totodile"}},
	[MINIGAME_BASE_ID + 219] ={{"@Flower Zone/Rayquaza's Balloon Panic/Chikorita"}},
	[MINIGAME_BASE_ID + 220] ={{"@Flower Zone/Rayquaza's Balloon Panic/Mime Jr."}},
	[MINIGAME_BASE_ID + 234] ={{"@Flower Zone/Rayquaza's Balloon Panic/Deoxys"}},
	[BASE_POKEMON_LOCATION_ID + 00193] ={{"@Flower Zone/Rayquaza's Balloon Panic/Deoxys Unlock"}},

	-- Skygarden
	[QUEST_BASE_ID + 21] = { { "@Skygarden/Mew/Challenge 1" } },
	[QUEST_BASE_ID + 22] = { { "@Skygarden/Mew/Challenge 2" } },
	[QUEST_BASE_ID + 23] = { { "@Skygarden/Mew/Challenge 3" } },
	[QUEST_BASE_ID + 24] = { { "@Skygarden/Mew/Challenge 4" } },
	[QUEST_BASE_ID + 25] = { { "@Skygarden/Mew/Challenge completed" } },
	[QUEST_BASE_ID + 26] = { { "@Skygarden/Mew/Completed Prisma Stage 1" } },
	[QUEST_BASE_ID + 27] = { { "@Skygarden/Mew/Completed Prisma Stage 2" } },
	[QUEST_BASE_ID + 28] = { { "@Skygarden/Mew/Completed Prisma Full" } },



}

